### ISSUE TITLE
boto3 usage may not be threadsafe

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse-s3-storage-provider#11]
When enabling this for the first time, it appears to automatically upload everything to s3 (OK!)
However, there seems to be a threading issue  and this causes this error:

```
 2018-08-23 17:58:36,257 - twisted - 131 - CRITICAL - - Unhandled Error
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run() 
   File "/usr/lib/python2.7/threading.py", line 754, in run 
     self.__target(*self.__args, **self.__kwargs)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
     task()
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
     task()
 --- <exception caught here> ---
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
     result = inContext.theWork()
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
     return self.currentContext().callWithContext(ctx, func, *args, **kw)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
     return func(*args,**kw)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/s3_storage_provider.py", line 57, in _store_file
     boto3.resource('s3').Bucket(self.bucket).upload_file(
   File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/__init__.py", line 100, in resource
     return _get_default_session().resource(*args, **kwargs)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/session.py", line 389, in resource
     aws_session_token=aws_session_token, config=config) 
   File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
     aws_session_token=aws_session_token, config=config) 
   File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 875, in create_client
     endpoint_resolver = self._get_internal_component('endpoint_resolver') 
   File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 744, in _get_internal_component
     return self._internal_components.get_component(name)
   File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 950, in get_component
     del self._deferred[name] 
 exceptions.KeyError: 'endpoint_resolver'
```

Apparently boto3's default client is not threadsafe, based on a brief googling around the internet.

**Comment by michaelkaye** [comment]
Got this in another part of the code: 
```
  File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/s3_storage_provider.py", line 57, in _store_file
    boto3.resource('s3').Bucket(self.bucket).upload_file(
  File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 878, in create_client
    credentials = self.get_credentials()
  File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 479, in get_credentials
    'credential_provider').load_credentials()
  File "/opt/synapse/env/local/lib/python2.7/site-packages/botocore/session.py", line 954, in get_component
    del self._deferred[name]
exceptions.KeyError: 'credential_provider'
```

**Comment by richvdh** [comment]
I believe this is fixed now
