### ISSUE TITLE
Storage Provider incompatible with Synapse 1.32.x

### ISSUE THREAD

**Issue by n0emis** [matrix-org/synapse-s3-storage-provider#55]
**Describe the bug**
This Storage Provider seems to be incompatible with the newest releases of synapse, so that viewing any media in a client does not work.

**To Reproduce**
1. Install/Update synapse version 1.32.x
2. Install the storage provider
3. Try to open any media in any client

<details> 

```
2021-04-21 15:58:44,039 - twisted - 260 - CRITICAL - sentinel - Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/s3_storage_provider.py", line 166, in s3_download_task
    with LoggingContext(parent_context=parent_logcontext):
builtins.TypeError: __init__() missing 1 required positional argument: 'name'
```

</details> 

**Expected behavior**
Vieweing media should wor

**Comment by ShadowJonathan** [comment]
@richvdh

**Comment by richvdh** [comment]
thank you
