### ISSUE TITLE
S3 storage provider stopped working

### ISSUE THREAD

**Issue by gergof** [matrix-org/synapse-s3-storage-provider#57]
**Describe the bug**
Yesterday it was running fine, but I upgraded synapse and now I'm getting errors.

**To Reproduce**
1. upgrade to synapse 1.34.0
2. try to get/upload any file from/to the media repo

**Expected behavior**
It should return or upload the image.

**Log**
This is a sample error:
```
synapse_1             | 2021-05-20 10:24:17,574 - synapse.http.server - 93 - ERROR - GET-4249 - Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x7fa50af7f400 method='GET' uri='/_matrix/media/r0/thumbnail/matrix.org/xxxxx?width=800&height=600&method=scale' clientproto='HTTP/1.1' site='8008'>
synapse_1             | Traceback (most recent call last):
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
synapse_1             |     callback_return = await self._async_render(request)
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 286, in _async_render
synapse_1             |     callback_return = await raw_callback_return
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 83, in _async_render_GET
synapse_1             |     await self._respond_remote_thumbnail(
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 260, in _respond_remote_thumbnail
synapse_1             |     media_info = await self.media_repo.get_remote_media_info(server_name, media_id)
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/media_repository.py", line 281, in get_remote_media_info
synapse_1             |     responder, media_info = await self._get_remote_media_impl(
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/media_repository.py", line 339, in _get_remote_media_impl
synapse_1             |     raise e
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/media_repository.py", line 328, in _get_remote_media_impl
synapse_1             |     media_info = await self._download_remote_file(
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/media_repository.py", line 431, in _download_remote_file
synapse_1             |     await finish()
synapse_1             |   File "/usr/local/lib/py-thon3.8/site-packages/synapse/rest/media/v1/media_storage.py", line 145, in finish
synapse_1             |     await provider.store_file(path, file_info)
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/media/v1/storage_provider.py", line 99, in store_file
synapse_1             |     await maybe_awaitable(self.backend.store_file(path, file_info))  # type: ignore
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
synapse_1             |     result = inContext.theWork()  # type: ignore[attr-defined]
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
synapse_1             |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
synapse_1             |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
synapse_1             |     return func(*args, **kw)
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/s3_storage_provider.py", line 121, in _store_file
synapse_1             |     self._get_s3_client().upload_file(
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
synapse_1             |     return transfer.upload_file(
synapse_1             |   File "/usr/local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 285, in upload_file
synapse_1             |     raise S3UploadFailedError(
synapse_1             | boto3.exceptions.S3UploadFailedError: Failed to upload /data/media_store/remote_content/matrix.org/xx/xx/xxxxxx to media.matrix.systemtest.tk/remote_content/matrix.org/xx/xx/xxxxxx: An error occurred (RequestTimeout) when calling the PutObject operation (reached max retries: 4): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

I get the same kind of errors when downloading files. On upload it fails as well.

When downloading:
```
 botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://s3.eu-west-1.amazonaws.com/media.matrix.systemtest.tk/remote_content/matrix.org/xx/xx/xxxxxx"
```

**Versions**
- Running in docker
- Synapse 1.34.0

**Additional Context**
- Bucket name is media.matrix.systemtest.tk

**Comment by gergof** [comment]
The CPU usage is below 10%. There's no problem with any other request.

**Comment by gergof** [comment]
After a few days the problem disappeared. I`m not really sure what was the cause (probably some kind of network problem).
